[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 'v:false'
lua_source = '''
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    disable = {},
  },
  indent = {
    enable = false,
  },
  yati = {
    enable = true,
  },
  ensure_installed = {
    "bash",
    "vim",
    "regex",
    "lua",
    "julia",
    "typescript",
    "json",
    "yaml",
    "toml",
    "markdown",
    "html",
    "css",
    "sql",
  },
}
'''

[[plugins]]
repo = 'nvim-treesitter/playground'
depends = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
repo = 'yioneko/nvim-yati'
depends = 'nvim-treesitter/nvim-treesitter'
