[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 'v:false'
hook_source = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    disable = {},
  },
  ensure_installed = {
    "bash",
    "vim",
    "regex",
    "lua",
    "julia",
    "typescript",
    "json",
    "yaml",
    "toml",
    "markdown",
    "html",
    "css",
  },
}
EOF
'''

[[plugins]]
repo = 'nvim-treesitter/playground'
depends = 'nvim-treesitter/nvim-treesitter'
