[[plugins]]
repo = 'romgrk/barbar.nvim'
depends = 'nvim-web-devicons' 
hook_add = '''
nnoremap <silent> <leader>1 :BufferGoto 1<CR>
nnoremap <silent> <leader>2 :BufferGoto 2<CR>
nnoremap <silent> <leader>3 :BufferGoto 3<CR>
nnoremap <silent> <leader>4 :BufferGoto 4<CR>
nnoremap <silent> <leader>5 :BufferGoto 5<CR>
nnoremap <silent> <leader>6 :BufferGoto 6<CR>
nnoremap <silent> <leader>7 :BufferGoto 7<CR>
nnoremap <silent> <leader>8 :BufferGoto 8<CR>
nnoremap <silent> <leader>9 :BufferGoto 9<CR>
nnoremap <silent> <leader>bj :BufferPick<CR>
nnoremap <silent> <leader>bp :BufferPin<CR>
nnoremap <silent> <leader>bc :BufferClose<CR>
nnoremap <silent> <leader>bC :BufferCloseAllButPinned<CR>
nnoremap <silent> <leader>bo :BufferOrderByLanguage<CR>
'''

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons' 
