[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
on_source = 'denops.vim'
hook_add = '''
function! s:ddu_rg() abort
  call ddu#start({
    \ 'volatile': v:true,
    \ 'sources': [{'name': 'rg'}],
    \ })
endfunction

function! s:ddu_file() abort
  call ddu#start({
    \ 'sources': [{'name': 'file_external'}],
    \ })
endfunction

function! s:ddu_config() abort
  call ddu#start({
    \ 'sources': [{'name': 'file_external', 'params': {'path': expand('~/.config/vim')}}],
    \ })
endfunction

function! s:ddu_tree() abort
  call ddu#start({
    \ 'ui': 'filer',
    \ 'sources': [{'name': 'file', 'params': {'path': expand('~')}}],
    \ })
endfunction

nnoremap <silent> <leader>ug <cmd>call <SID>ddu_rg()<CR>
nnoremap <silent> <leader>uf <cmd>call <SID>ddu_file()<CR>
nnoremap <silent> <leader>uc <cmd>call <SID>ddu_config()<CR>
nnoremap <silent> <leader>ut <cmd>call <SID>ddu_tree()<CR>
'''
hook_source = '''
call ddu#custom#patch_global({
    \   'ui': 'ff',
    \   'uiParams': {
    \     'ff': {
    \       'startFilter': v:true,
    \     },
    \   },
    \   'sourceOptions': {
    \     'file_external': {
    \       'matchers': ['matcher_fzf'],
    \     },
    \     'rg': {
    \       'matchers': [],
    \     },
    \     'file' :{
    \       'columns': ['filename'],
    \     },
    \   },
    \   'sourceParams': {
    \     'file_external': {
    \       'cmd': ['git', 'ls-files', '-co', '--exclude-standard'],
    \     },
    \     'rg': {
    \       'args': ['--column', '--no-heading', '--color', 'never'],
    \     },
    \   },
    \   'kindOptions': {
    \     'file': {
    \       'defaultAction': 'open',
    \     },
    \   },
    \ })

if has('nvim')
  call ddu#custom#patch_global({
    \   'uiParams': {
    \     'ff': {
    \       'split': 'floating',
    \       'filterFloatingPosition': 'top',
    \       'filterSplitDirection': 'floating',
    \       'floatingBorder': 'none',
    \     },
    \   }
    \ })
endif
'''

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'

[plugins.ftplugin]
ddu-ff = '''
nnoremap <buffer><silent> <CR>
\ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
nnoremap <buffer><silent> <Space>
\ <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
nnoremap <buffer><silent> i
\ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
nnoremap <buffer><silent> q
\ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
'''
ddu-ff-filter = '''
inoremap <buffer><silent> <CR>
\ <Esc><Cmd>close<CR>
nnoremap <buffer><silent> <CR>
\ <Cmd>close<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'
hook_source = '''
call ddu#custom#patch_global({
    \   'uiParams': {
    \     'filer': {
    \       'split': 'floating',
    \     },
    \   },
    \ })
'''
[plugins.ftplugin]
ddu-filer = '''
nnoremap <buffer><silent> <CR>
      \ <Cmd>call ddu#ui#filer#do_action('itemAction')<CR>
nnoremap <buffer><silent> <Space>
      \ <Cmd>call ddu#ui#filer#do_action('toggleSelectItem')<CR>
nnoremap <buffer> o
      \ <Cmd>call ddu#ui#filer#do_action('expandItem',
      \ {'mode': 'toggle'})<CR>
nnoremap <buffer><silent> q
      \ <Cmd>call ddu#ui#filer#do_action('quit')<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-column-filename'
on_source = 'ddu.vim'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-file_external'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'
