[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'vim-denops/denops.vim'
hook_add = '''
call ddu#custom#patch_global({
    \ 'ui': 'std',
    \ })

" Specify matcher
call ddu#custom#patch_global({
    \   'sourceOptions': {
    \     '_': {
    \       'matchers': ['matcher_fzf'],
    \     },
    \   }
    \ })

" Set default sources
call ddu#custom#patch_global({
    \   'sources': [{'name': 'file', 'params': {}}],
    \   })

" Keymappings
nnoremap <silent> <leader>u <cmd>call ddu#start({})<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-ui-std'
hook_add = '''
autocmd FileType ddu-std call s:ddu_my_settings()
function! s:ddu_my_settings() abort
  nnoremap <buffer><silent> <CR>
  \ <Cmd>call ddu#ui#std#do_map('doAction', {'name' : 'default'})<CR>
  nnoremap <buffer><silent> <Space>
  \ <Cmd>call ddu#ui#std#do_map('toggleSelectItem')<CR>
  nnoremap <buffer><silent> i
  \ <Cmd>call ddu#ui#std#do_map('openFilterWindow')<CR>
  nnoremap <buffer><silent> q
  \ <Cmd>call ddu#ui#std#do_map('quit')<CR>
endfunction

autocmd FileType ddu-std-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
  inoremap <buffer><silent> <CR>
  \ <Esc><Cmd>close<CR>
  nnoremap <buffer><silent> <CR>
  \ <Cmd>close<CR>
endfunction
'''


[[plugins]]
repo = 'Shougo/ddu-source-file'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
