[[plugins]]
repo = 'hasundue/vim-keycasty'
depends = 'denops.vim'
merged = 'v:false'

[[plugins]]
repo = 'hasundue/vim-reactive'
depends = 'denops.vim'
merged = 'v:false'
hook_add = '''
nnoremap <silent> <LocalLeader>ra :call reactive#attach()<CR>
nnoremap <silent> <LocalLeader>rd :call reactive#debug()<CR>
'''

[[plugins]]
repo = 'hasundue/vim-pluto'
depends = 'denops.vim'
on_ft = 'julia'
hook_source = '''
nnoremap <silent> <LocalLeader>O :call pluto#insert_cell_above()<CR>
nnoremap <silent> <LocalLeader>o :call pluto#insert_cell_below()<CR>
nnoremap <silent> <LocalLeader>t :call pluto#toggle_code()<CR>
nnoremap <silent> <LocalLeader>dd :call pluto#delete_cell()<CR>
nnoremap <silent> <LocalLeader>yy :call pluto#yank_cell()<CR>
nnoremap <silent> <LocalLeader>P :call pluto#paste_cell_above()<CR>
nnoremap <silent> <LocalLeader>p :call pluto#paste_cell_below()<CR>
'''
