[[plugins]]
repo = 'ellisonleao/glow.nvim'
on_ft = 'markdown'
hook_add = '''
nnoremap <LocalLeader>p :Glow<CR>
'''

[[plugins]]
repo = 'psliwka/vim-dirtytalk'
on_ft = 'markdown'
hook_post_update = ':DirtytalkUpdate'

[[plugins]]
repo = 'hasundue/glance-vim'
depends = 'denops.vim'
on_ft = 'markdown'
hook_add = '''
let g:glance#stylesheet = '@import url("https://cdn.simplecss.org/simple.min.css");'
let g:glance#markdown_html = v:true
let g:glance#markdown_linkify = v:true
let g:glance#markdown_breaks = v:true
let g:glance#markdown_plugins = [
  \ 'https://esm.sh/markdown-it-emoji',
  \ 'https://esm.sh/markdown-it-task-lists',
  \ ]
'''

[[plugins]]
repo = 'skanehira/gyazo.vim'
on_ft = 'markdown'

[[plugins]]
repo = 'skanehira/denops-germanium.vim'
depends = 'denops.vim'
on_ft = 'markdown'
